#!/bin/env bash

memoryall(){
    ram=$(free -h | awk '/^Mem:/{print "'"${1} "'"$3}')
    swap=$(free -h | awk -v icon=${1:-} '/^Swap:/{print "'"${1}"' "$3}')
    echo "RAM: "$ram
    echo "SWAP: "$swap
}
echo $(memoryall)
